"""Tests for the Codex CLI sync target."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional

import pytest

from aes.targets._base import AES_SENTINEL_MD, AgentContext
from aes.targets.codex import CodexTarget


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_ctx(
    tmp_path: Path,
    manifest: Optional[dict] = None,
    permissions: Optional[dict] = None,
    skill_runbooks: Optional[Dict[str, str]] = None,
    skill_metadata: Optional[Dict[str, Dict[str, Any]]] = None,
    instructions: str = "Test instructions.",
    orchestrator: Optional[str] = None,
    memory_project: Optional[str] = None,
) -> AgentContext:
    """Build a minimal AgentContext for testing."""
    agent_dir = tmp_path / ".agent"
    agent_dir.mkdir(exist_ok=True)
    return AgentContext(
        project_root=tmp_path,
        agent_dir=agent_dir,
        manifest=manifest or {"name": "test-project", "version": "1.0.0"},
        instructions=instructions,
        orchestrator=orchestrator,
        skill_runbooks=skill_runbooks or {},
        permissions=permissions,
        commands=[],
        memory_project=memory_project,
        skill_metadata=skill_metadata or {},
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

class TestCodexGeneration:
    """Test Codex target file generation."""

    def test_agents_md_generated(self, tmp_path: Path) -> None:
        ctx = _make_ctx(tmp_path)
        target = CodexTarget()
        plan = target.plan(ctx, force=False)

        agents_file = [f for f in plan.files if f.relative_path == "AGENTS.md"]
        assert len(agents_file) == 1
        content = agents_file[0].content
        assert "Generated by `aes sync`" in content
        assert "test-project" in content
        assert "Test instructions." in content

    def test_agents_md_has_codex_header(self, tmp_path: Path) -> None:
        ctx = _make_ctx(tmp_path, manifest={"name": "My App"})
        plan = CodexTarget().plan(ctx, force=False)

        content = plan.files[0].content
        assert "# My App — Agent Instructions" in content

    def test_agents_md_includes_orchestrator(self, tmp_path: Path) -> None:
        ctx = _make_ctx(tmp_path, orchestrator="## Orchestration rules here")
        plan = CodexTarget().plan(ctx, force=False)

        content = plan.files[0].content
        assert "Orchestration rules here" in content

    def test_agents_md_includes_memory(self, tmp_path: Path) -> None:
        ctx = _make_ctx(tmp_path, memory_project="## Memory context")
        plan = CodexTarget().plan(ctx, force=False)

        content = plan.files[0].content
        assert "Memory context" in content

    def test_permissions_as_markdown(self, tmp_path: Path) -> None:
        perms = {
            "allow": {
                "files": {"write": ["src/**"]},
                "shell": {"execute": ["npm test", "npm run build"]},
            },
            "deny": {
                "shell": ["rm -rf /"],
            },
        }
        ctx = _make_ctx(tmp_path, permissions=perms)
        plan = CodexTarget().plan(ctx, force=False)

        content = plan.files[0].content
        assert "## Permissions" in content
        assert "`src/**`" in content
        assert "Never run: `rm -rf /`" in content

    def test_no_permissions_section_when_empty(self, tmp_path: Path) -> None:
        ctx = _make_ctx(tmp_path, permissions={})
        plan = CodexTarget().plan(ctx, force=False)

        content = plan.files[0].content
        assert "## Permissions" not in content


class TestCodexSkills:
    """Test Codex skill file generation."""

    def test_skill_files_generated(self, tmp_path: Path) -> None:
        ctx = _make_ctx(
            tmp_path,
            skill_runbooks={"discover": "# Discover\nFind data sources."},
            skill_metadata={
                "discover": {
                    "name": "Discover",
                    "description": "Find data sources",
                    "activation": "explicit",
                },
            },
        )
        plan = CodexTarget().plan(ctx, force=False)

        skill_files = [
            f for f in plan.files
            if f.relative_path.startswith(".agents/skills/")
        ]
        assert len(skill_files) == 1
        assert skill_files[0].relative_path == ".agents/skills/discover/SKILL.md"

    def test_skill_has_sentinel(self, tmp_path: Path) -> None:
        ctx = _make_ctx(
            tmp_path,
            skill_runbooks={"train": "# Train\nTrain models."},
            skill_metadata={"train": {"name": "Train", "description": "Train models"}},
        )
        plan = CodexTarget().plan(ctx, force=False)

        skill_file = [
            f for f in plan.files if "train" in f.relative_path
        ][0]
        assert "Generated by `aes sync`" in skill_file.content

    def test_skill_has_yaml_frontmatter(self, tmp_path: Path) -> None:
        ctx = _make_ctx(
            tmp_path,
            skill_runbooks={"deploy": "# Deploy\nDeploy to prod."},
            skill_metadata={
                "deploy": {
                    "name": "Deploy",
                    "description": "Deploy to production",
                    "version": "1.2.0",
                    "license": "Apache-2.0",
                },
            },
        )
        plan = CodexTarget().plan(ctx, force=False)

        skill_file = [
            f for f in plan.files if "deploy" in f.relative_path
        ][0]
        content = skill_file.content
        assert "name: Deploy" in content
        assert "description: Deploy to production" in content
        assert "version: 1.2.0" in content
        assert "license: Apache-2.0" in content

    def test_skill_includes_negative_triggers(self, tmp_path: Path) -> None:
        ctx = _make_ctx(
            tmp_path,
            skill_runbooks={"review": "# Review\nReview code."},
            skill_metadata={
                "review": {
                    "name": "Review",
                    "description": "Code review",
                    "negative_triggers": [
                        "Do not use for documentation-only changes",
                        "Skip for auto-generated files",
                    ],
                },
            },
        )
        plan = CodexTarget().plan(ctx, force=False)

        skill_file = [
            f for f in plan.files if "review" in f.relative_path
        ][0]
        content = skill_file.content
        assert "Do NOT Use When" in content
        assert "documentation-only changes" in content
        assert "auto-generated files" in content

    def test_skill_includes_permissions(self, tmp_path: Path) -> None:
        ctx = _make_ctx(
            tmp_path,
            skill_runbooks={"build": "# Build\nBuild project."},
            skill_metadata={
                "build": {
                    "name": "Build",
                    "description": "Build the project",
                    "allowed_tools": {
                        "shell": True,
                        "files": {"read": True, "write": ["dist/**"]},
                        "network": False,
                    },
                },
            },
        )
        plan = CodexTarget().plan(ctx, force=False)

        skill_file = [
            f for f in plan.files if "build" in f.relative_path
        ][0]
        content = skill_file.content
        assert "Skill Permissions" in content
        assert "Shell: allowed" in content
        assert "Network: denied" in content

    def test_skill_index_references_agents_skills_path(self, tmp_path: Path) -> None:
        ctx = _make_ctx(
            tmp_path,
            skill_runbooks={"analyze": "# Analyze"},
            skill_metadata={
                "analyze": {
                    "name": "Analyze",
                    "description": "Analyze data",
                    "activation": "explicit",
                },
            },
        )
        plan = CodexTarget().plan(ctx, force=False)

        agents_md = [f for f in plan.files if f.relative_path == "AGENTS.md"][0]
        content = agents_md.content
        # Should reference .agents/skills/ path, not /skills/ slash commands
        assert ".agents/skills/analyze" in content
        assert "/skills/analyze" not in content or ".agents/skills/analyze" in content

    def test_multiple_skills(self, tmp_path: Path) -> None:
        ctx = _make_ctx(
            tmp_path,
            skill_runbooks={
                "discover": "# Discover",
                "train": "# Train",
                "evaluate": "# Evaluate",
            },
            skill_metadata={
                "discover": {"name": "Discover", "description": "Find data"},
                "train": {"name": "Train", "description": "Train models"},
                "evaluate": {"name": "Evaluate", "description": "Evaluate models"},
            },
        )
        plan = CodexTarget().plan(ctx, force=False)

        skill_files = [
            f for f in plan.files
            if f.relative_path.startswith(".agents/skills/")
        ]
        assert len(skill_files) == 3
        paths = {f.relative_path for f in skill_files}
        assert ".agents/skills/discover/SKILL.md" in paths
        assert ".agents/skills/train/SKILL.md" in paths
        assert ".agents/skills/evaluate/SKILL.md" in paths


class TestCodexConflictDetection:
    """Test conflict detection for Codex target."""

    def test_new_file_is_create(self, tmp_path: Path) -> None:
        ctx = _make_ctx(tmp_path)
        plan = CodexTarget().plan(ctx, force=False)

        assert plan.files[0].action == "create"

    def test_existing_sentinel_file_is_update(self, tmp_path: Path) -> None:
        agents_md = tmp_path / "AGENTS.md"
        agents_md.write_text(AES_SENTINEL_MD + "\nOld content")

        ctx = _make_ctx(tmp_path)
        plan = CodexTarget().plan(ctx, force=False)

        assert plan.files[0].action == "update"

    def test_existing_user_file_is_conflict(self, tmp_path: Path) -> None:
        agents_md = tmp_path / "AGENTS.md"
        agents_md.write_text("# My custom AGENTS.md\nDo not overwrite.")

        ctx = _make_ctx(tmp_path)
        plan = CodexTarget().plan(ctx, force=False)

        assert plan.files[0].action == "conflict"

    def test_force_overrides_conflict(self, tmp_path: Path) -> None:
        agents_md = tmp_path / "AGENTS.md"
        agents_md.write_text("# My custom AGENTS.md\nDo not overwrite.")

        ctx = _make_ctx(tmp_path)
        plan = CodexTarget().plan(ctx, force=True)

        assert plan.files[0].action == "update"
