"""Tests for aes sync command."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import yaml
from click.testing import CliRunner

from aes.__main__ import cli

EXAMPLES_DIR = Path(__file__).resolve().parent.parent.parent / "examples"


def _copy_example(name: str, dest: Path) -> Path:
    """Copy an example project into a temp directory."""
    src = EXAMPLES_DIR / name
    project = dest / "project"
    shutil.copytree(src, project)
    return project


class TestSyncCommand:
    """Test the CLI command itself."""

    def test_sync_requires_agent_dir(self, tmp_path: Path) -> None:
        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(tmp_path)])
        assert result.exit_code == 1
        assert "No .agent/" in result.output

    def test_sync_requires_manifest(self, tmp_path: Path) -> None:
        (tmp_path / ".agent").mkdir()
        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(tmp_path)])
        assert result.exit_code == 1
        assert "No agent.yaml" in result.output

    def test_sync_ml_pipeline_claude(self, tmp_path: Path) -> None:
        project = _copy_example("ml-pipeline", tmp_path)
        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(project), "-t", "claude"])
        assert result.exit_code == 0
        assert "CLAUDE.md" in result.output

        # CLAUDE.md created with sentinel and content
        claude_md = project / "CLAUDE.md"
        assert claude_md.exists()
        content = claude_md.read_text()
        assert "Generated by `aes sync`" in content
        assert "ML Model Factory" in content

        # settings.local.json created with permissions
        settings_path = project / ".claude" / "settings.local.json"
        assert settings_path.exists()
        settings = json.loads(settings_path.read_text())
        assert "permissions" in settings
        allow = settings["permissions"]["allow"]
        assert "Bash(git status)" in allow
        assert "Read(**/*)" in allow

        # Commands synced
        train_cmd = project / ".claude" / "commands" / "train.md"
        assert train_cmd.exists()
        assert "Generated by `aes sync`" in train_cmd.read_text()

    def test_sync_ml_pipeline_cursor(self, tmp_path: Path) -> None:
        project = _copy_example("ml-pipeline", tmp_path)
        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(project), "-t", "cursor"])
        assert result.exit_code == 0

        cursorrules = project / ".cursorrules"
        assert cursorrules.exists()
        content = cursorrules.read_text()
        assert "Generated by `aes sync`" in content
        assert "ML Model Factory" in content
        assert "Never Run These Commands" in content

    def test_sync_all_targets(self, tmp_path: Path) -> None:
        project = _copy_example("ml-pipeline", tmp_path)
        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(project)])
        assert result.exit_code == 0

        assert (project / "CLAUDE.md").exists()
        assert (project / ".cursorrules").exists()
        assert (project / ".github" / "copilot-instructions.md").exists()
        assert (project / ".windsurfrules").exists()

    def test_sync_dry_run(self, tmp_path: Path) -> None:
        project = _copy_example("ml-pipeline", tmp_path)
        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(project), "--dry-run"])
        assert result.exit_code == 0
        assert "Dry run" in result.output
        assert not (project / "CLAUDE.md").exists()
        assert not (project / ".aes-sync.json").exists()

    def test_sync_idempotent(self, tmp_path: Path) -> None:
        project = _copy_example("ml-pipeline", tmp_path)
        runner = CliRunner()

        # First sync
        runner.invoke(cli, ["sync", str(project), "-t", "claude"])
        content1 = (project / "CLAUDE.md").read_text()

        # Second sync
        result = runner.invoke(cli, ["sync", str(project), "-t", "claude"])
        assert result.exit_code == 0
        content2 = (project / "CLAUDE.md").read_text()
        assert content1 == content2

    def test_sync_conflict_detection(self, tmp_path: Path) -> None:
        project = _copy_example("ml-pipeline", tmp_path)
        # Write a hand-crafted CLAUDE.md without sentinel
        (project / "CLAUDE.md").write_text("# My hand-written instructions\n")

        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(project), "-t", "claude"])
        assert result.exit_code == 1
        assert "Conflict" in result.output

    def test_sync_force_overwrites(self, tmp_path: Path) -> None:
        project = _copy_example("ml-pipeline", tmp_path)
        (project / "CLAUDE.md").write_text("# Hand-written\n")

        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(project), "-t", "claude", "--force"])
        assert result.exit_code == 0
        content = (project / "CLAUDE.md").read_text()
        assert "Generated by `aes sync`" in content

    def test_sync_clean(self, tmp_path: Path) -> None:
        project = _copy_example("ml-pipeline", tmp_path)
        runner = CliRunner()

        # Sync first
        runner.invoke(cli, ["sync", str(project), "-t", "claude"])
        assert (project / "CLAUDE.md").exists()
        assert (project / ".claude" / "settings.local.json").exists()

        # Clean
        result = runner.invoke(cli, ["sync", str(project), "--clean"])
        assert result.exit_code == 0
        assert not (project / "CLAUDE.md").exists()
        assert not (project / ".claude" / "settings.local.json").exists()

    def test_sync_manifest_tracks_files(self, tmp_path: Path) -> None:
        project = _copy_example("ml-pipeline", tmp_path)
        runner = CliRunner()
        runner.invoke(cli, ["sync", str(project), "-t", "claude"])

        manifest_path = project / ".aes-sync.json"
        assert manifest_path.exists()
        manifest = json.loads(manifest_path.read_text())
        assert "CLAUDE.md" in manifest["files"]
        assert manifest["files"]["CLAUDE.md"]["target"] == "claude"
        assert manifest["synced_at"] is not None


class TestPermissionsTranslation:
    """Test the permission translation logic."""

    def test_ml_pipeline_permissions(self) -> None:
        from aes.targets._composer import translate_permissions_to_claude

        perms_path = EXAMPLES_DIR / "ml-pipeline" / ".agent" / "permissions.yaml"
        with open(perms_path) as f:
            permissions = yaml.safe_load(f)

        result = translate_permissions_to_claude(permissions)
        allow = result["permissions"]["allow"]
        deny = result["permissions"]["deny"]

        # Shell read -> Bash()
        assert "Bash(git status)" in allow
        assert "Bash(git log *)" in allow
        assert "Bash(git diff *)" in allow

        # Shell execute -> Bash()
        assert "Bash(python scripts/run_pipeline.py *)" in allow
        assert "Bash(python -m pytest *)" in allow

        # File read -> Read()
        assert "Read(**/*)" in allow

        # File write -> Write() + Edit()
        assert "Write(config/model_registry.py)" in allow
        assert "Edit(config/model_registry.py)" in allow

        # Deny shell -> Bash()
        assert "Bash(rm -rf *)" in deny
        assert "Bash(docker rm *)" in deny

        # Deny file write -> Write() + Edit()
        assert "Write(.env)" in deny
        assert "Edit(.env)" in deny

    def test_empty_permissions(self) -> None:
        from aes.targets._composer import translate_permissions_to_claude

        result = translate_permissions_to_claude({"aes_permissions": "1.0"})
        assert result == {"permissions": {}}

    def test_overrides_applied(self) -> None:
        from aes.targets._composer import translate_permissions_to_claude

        permissions = {
            "aes_permissions": "1.0",
            "allow": {"shell": {"read": ["git status"]}},
            "overrides": {
                "claude": {
                    "permissions": {
                        "allow": ["Bash(ssh:*)"],
                    }
                }
            },
        }
        result = translate_permissions_to_claude(permissions)
        allow = result["permissions"]["allow"]
        assert "Bash(git status)" in allow
        assert "Bash(ssh:*)" in allow


class TestWebAppExample:
    """Test sync works with the web-app example too."""

    def test_sync_web_app(self, tmp_path: Path) -> None:
        project = _copy_example("web-app", tmp_path)
        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(project)])
        assert result.exit_code == 0
        assert (project / "CLAUDE.md").exists()
        assert (project / ".cursorrules").exists()


class TestDevOpsExample:
    """Test sync works with the devops example."""

    def test_sync_devops(self, tmp_path: Path) -> None:
        project = _copy_example("devops", tmp_path)
        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(project)])
        assert result.exit_code == 0
        assert (project / "CLAUDE.md").exists()


class TestLocalConfigMerge:
    """Test that local.yaml permissions are deep-merged during sync."""

    def test_local_permissions_appear_in_synced_output(self, tmp_path: Path) -> None:
        project = _copy_example("ml-pipeline", tmp_path)
        # Create a local.yaml with extra SSH permission
        local_yaml = project / ".agent" / "local.yaml"
        local_yaml.write_text(
            "permissions:\n"
            "  allow:\n"
            "    shell:\n"
            "      remote:\n"
            "        - \"ssh -i ~/.ssh/my_key user@myhost *\"\n"
        )
        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(project), "-t", "claude"])
        assert result.exit_code == 0

        # The SSH command from local.yaml should appear in Claude settings
        settings_path = project / ".claude" / "settings.local.json"
        settings = json.loads(settings_path.read_text())
        allow = settings["permissions"]["allow"]
        assert any("ssh" in p and "my_key" in p for p in allow)

    def test_sync_works_without_local_yaml(self, tmp_path: Path) -> None:
        project = _copy_example("ml-pipeline", tmp_path)
        # Ensure no local.yaml exists
        local_path = project / ".agent" / "local.yaml"
        if local_path.exists():
            local_path.unlink()
        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(project), "-t", "claude"])
        assert result.exit_code == 0
        assert (project / "CLAUDE.md").exists()

    def test_local_deny_extends_base_deny(self, tmp_path: Path) -> None:
        project = _copy_example("ml-pipeline", tmp_path)
        local_yaml = project / ".agent" / "local.yaml"
        local_yaml.write_text(
            "permissions:\n"
            "  deny:\n"
            "    shell:\n"
            "      - \"sudo *\"\n"
        )
        runner = CliRunner()
        result = runner.invoke(cli, ["sync", str(project), "-t", "claude"])
        assert result.exit_code == 0

        settings_path = project / ".claude" / "settings.local.json"
        settings = json.loads(settings_path.read_text())
        deny = settings["permissions"]["deny"]
        # Original deny entries should still be present
        assert "Bash(rm -rf *)" in deny
        # New local deny should also be present
        assert "Bash(sudo *)" in deny
