"""Base types for sync target adapters."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional


# Sentinels embedded in generated files to detect aes sync output
AES_SENTINEL_MD = "<!-- Generated by `aes sync` \u2014 DO NOT EDIT MANUALLY -->"
AES_SENTINEL_JSON_KEY = "_aes_sync"


@dataclass
class AgentContext:
    """Parsed .agent/ contents, passed to every adapter."""

    project_root: Path
    agent_dir: Path
    manifest: dict
    instructions: Optional[str]
    orchestrator: Optional[str]
    skill_runbooks: Dict[str, str]
    permissions: Optional[dict]
    commands: List[dict]
    memory_project: Optional[str]
    local_config: Optional[dict] = None


@dataclass
class GeneratedFile:
    """A single file to be generated by sync."""

    relative_path: str
    content: str
    description: str
    action: str = "create"  # create | update | conflict


@dataclass
class SyncPlan:
    """What a target adapter wants to generate."""

    target_name: str
    files: List[GeneratedFile] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)


class SyncTarget(ABC):
    """Abstract base for a tool target adapter."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Tool name, e.g. 'claude'."""

    @abstractmethod
    def plan(self, ctx: AgentContext, force: bool) -> SyncPlan:
        """Generate a plan of files to create/update."""

    def _check_conflict(self, project_root: Path, rel_path: str, force: bool) -> str:
        """Determine the action for a file path.

        Returns 'create', 'update', or 'conflict'.
        """
        full_path = project_root / rel_path
        if not full_path.exists():
            return "create"
        content = full_path.read_text()
        if AES_SENTINEL_MD in content or f'"{AES_SENTINEL_JSON_KEY}"' in content:
            return "update"
        if force:
            return "update"
        return "conflict"
